# Generated by Django 4.2 on 2023-04-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('accounty_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Month_saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('today_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=100)),
                ('accounts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='interest.accounts')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.month_saving')),
            ],
        ),
    ]
